src/UniProject/Controllers/CommentController.cs
namespace Contollers;
using Microsoft.AspNetCore.Mvc;

public class CommentController : Controller
{
    [Route("Comments")]
    public ActionResult Index()
    {
        return View();
    }
}

src/UniProject/Controllers/HomeController.cs
namespace Contollers;

using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

public class HomeController : Controller
{
    [Route("/")]
    public ActionResult Index()
    {
        return View();
    }

    [Route("/Error")]
    public IActionResult Error(string message)
    {
        var exceptionFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
        if (exceptionFeature != null)
        {
            var exception = exceptionFeature.Error;

            Console.WriteLine(exception);

            ViewData["ErrorMessage"] = exception.Message;
        }
        else
        {
            ViewData["ErrorMessage"] = "An unknown error occurred.";
        }

        return View();
    }
}

src/UniProject/Controllers/PostController.cs
namespace Contollers;
using Microsoft.AspNetCore.Mvc;

public class PostController : Controller
{
    [Route("Posts")]
    public ActionResult Index()
    {
        return View();
    }
}

src/UniProject/Controllers/UserController.cs
namespace Controllers;
using AutoMapper;
using Contollers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Services;
using DTOs;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

[Route("Users")]
public class UserController : Controller
{
    private readonly IUserService _userService;
    private readonly IMapper _mapper;

    public UserController(IUserService userService, IMapper mapper)
    {
        _userService = userService;
        _mapper = mapper;
    }

    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        try
        {
            var tempUsers = await _userService.GetAllUsers(); 
            var users = new List<ResponseUserDto>();
            foreach(var user in tempUsers)
                users.Add(_mapper.Map<ResponseUserDto>(user));
            return View(users);
        }
        catch(Exception e)
        {
            throw new Exception("Something Bad happend :( !", e);   
        }
    }

    [HttpGet("Details/{id}")]
    public async Task<IActionResult> Details(int id)
    {  
        try
        {
            var user = _mapper.Map<ResponseUserDto>(await _userService.GetUserById(id));
            return View(user);
        }
        catch (Exception e)
        {
            throw new Exception($"Could not Get Details about user with Id {id}", e);
        }
    } 

    [HttpGet("Delete/{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            var user = _mapper.Map<ResponseUserDto>(await _userService.GetUserById(id));
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        catch (Exception e)
        {
            throw new Exception($"Could Not Delete User With Id:{id}", e);
        }
    }

    [HttpPost("Delete/{id}")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        try
        {
            await _userService.DeleteUserById(id);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            throw new Exception($"Could Not Delete User With Id:{id}", e);
        }
    }

    [HttpGet("Create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("Create")]
    public async Task<IActionResult> Create(RequestUserDto requestUserDto)
    {
        try
        {
            var user = _mapper.Map<UserDto>(requestUserDto);
            await _userService.CreateUser(user);

            return RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            throw new Exception("Could Not Create New User ", e);
        }
        
    }


    [HttpGet("Post/{id}")]
    public async Task<IActionResult> Update(int id)
    {
        try
        {
            var user = await _userService.GetUserById(id); 

            var model = new RequestUserDto
            {
                Username = user.Username,
                UnhashedPassword = "",
            };

            return View(model);
        }
        catch(Exception e)
        {
            throw new Exception($"Could Not Update User With Id: {id}", e);
        }
    }

    [HttpPost("Post/{id}")]
    public async Task<IActionResult> Update(int id, RequestUserDto user)
    {
        try
        {
            var updatedUser = _mapper.Map<UpdateUserDto>(user);
            updatedUser.UserId = id; 
            await _userService.UpdateUser(updatedUser);

            return RedirectToAction("Index"); 
        }
        catch(Exception e)
        {
            throw new Exception($"Could Not Update User With Id: {id}", e);
        }
    }
}

src/UniProject/Views/Comment/Index.cshtml
<h1>Nothing is Here :P </h1>

<a href="@Url.Action("Index", "Home")" class="btn btn-success">Go to Home</a>

src/UniProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>Home Page</h2>

<ul>
    <li>@Html.ActionLink("Posts", "Index", "Post")</li>
    <li>@Html.ActionLink("Users", "Index", "User")</li>
    <li>@Html.ActionLink("Comments", "Index", "Comment")</li>
</ul>

src/UniProject/Views/Post/Index.cshtml
<h1>Nothing is Here :P </h1>

<a href="@Url.Action("Index", "Home")" class="btn btn-success">Go to Home</a>

src/UniProject/Views/User/Create.cshtml
@using DTOs
@model RequestUserDto

<h2>Create User</h2>


<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Username" class="control-label">Username:</label>
        <input asp-for="Username" class="form-control" name="Username" />
    </div>

    <div class="form-group">
        <label asp-for="UnhashedPassword" class="control-label">Password:</label>
        <input asp-for="UnhashedPassword" class="form-control" type="password" name="UnhashedPassword" />
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>
<a href="@Url.Action("Index","User")" class="btn btn-success">Back</a>

src/UniProject/Views/User/Delete.cshtml
<h2>Delete User</h2>
@using DTOs

<h3>Are you sure you want to delete this user?</h3>
<div>
    <h4>Username: @Model.Username</h4>
    <h4>UserID: @Model.UserId</h4>

    <form asp-action="DeleteConfirmed" asp-route-id="@Model.UserId" method="post">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Cancel</a>
    </form>
</div>
<a href="@Url.Action("Index","User")" class="btn btn-success">Back</a>

src/UniProject/Views/User/Details.cshtml
@using DTOs

<h1>Details</h1>    
@if (Model != null)
{
    <table>
        <tr>
            <th>UserId</th>
            <th>UserName</th>
        </tr>
        <tr>
            <td>@Model.UserId</td>
            <td>@Model.Username</td>
        </tr>
    </table>
}
else
{
    <p>No user found.</p>
}

<a href="@Url.Action("Index","User")" class="btn btn-success">Back</a>

src/UniProject/Views/User/Index.cshtml
@using DTOs
@model IEnumerable<ResponseUserDto>

@if (Model != null && Model.Any())
{
    <table>
        <tr>
            <th>UserId</th>
            <th>UserName</th>
            <th>Actions</th>
        </tr>
        @foreach(var user in Model)
        {
            <tr>
                <td>@user.UserId</td>
                <td>@user.Username</td>
                <td>
                    <a href="@Url.Action("Details", "User", new { id = user.UserId })" class="btn btn-info">Details</a>
                    <a href="@Url.Action("Update", "User", new { id = user.UserId })" class="btn btn-primary">Edit</a>
                    <a href="@Url.Action("Delete", "User", new { id = user.UserId })" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>No user found.</p>
}

<a href="@Url.Action("Create", "User")" class="btn btn-success">Create New User</a>
<br>
<a href="@Url.Action("Index", "Home")" class="btn btn-success">Go to Home</a>

src/UniProject/Views/User/Update.cshtml
@using DTOs
@model RequestUserDto

<h2>Update User</h2>

<form asp-action="Update" asp-route-id="@ViewContext.RouteData.Values["id"]" method="post">
    <div class="form-group">
        <label asp-for="Username" class="control-label">New Username:</label>
        <input asp-for="Username" class="form-control" name="Username"/>
    </div>

    <div class="form-group">
        <label asp-for="UnhashedPassword" class="control-label">New Password:</label>
        <input asp-for="UnhashedPassword" class="form-control" type="password" name="UnhashedPassword"/>
    </div>

    <div class="form-group">
        <input type="submit" value="Update" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>